### ISSUE TITLE
Support go1.13

### ISSUE THREAD

**Issue by djmitche** [taskcluster/websocktunnel#46]
With go1.13, the tests fail.  Fix that :)

**Comment by richardgreg** [comment]
@djmitche I would like to have a crack at this :)

**Comment by djmitche** [comment]
Give it a shot!  Start by running the tests in go1.13.  The test failures have to do with websocket support, so it might help to try to figure out what changed in websockets between go1.12 and go1.13.  Likely one of the tests is doing something silly that accidentally worked in go1.12 but doesn't work anymore in go1.13.

**Comment by richardgreg** [comment]
@djmitche the 'bad handshake' error is caused by the space in the key-name when setting header's key-value pair. go1.12 accepted and normalized it but the latest go version does not. This is due to security issues. https://github.com/golang/go/commit/5a6ab1ec3e678640befebeb3318b746a64ad986c

`TestConcurrentConnections` fails on my machine raising `connect: connection reset by peer` error. Does the function behave differently on different machines?

**Comment by djmitche** [comment]
The first part sounds like a good fix even in go1.12.   Want to make a PR to clean that up while investigating other issues?

Judging by the "Concurrent" in the name, I would suppose that test case can behave differently depending on lots of things, including machine and maybe just randomness.

**Comment by richardgreg** [comment]
Sure! I'll make a PR.

**Comment by djmitche** [comment]
I landed a few changes on master to update CI to use go1.13 as well.  That required an update to golangci-lint, which required fixing another lint, but otherwise not a big deal.  Thanks!

**Comment by richardgreg** [comment]
Alright. You're welcome.
